[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
naengs_solana_nft_permission = "7aRToA2uP6zKZRJgJFxfnxJjA69mJKVXWE7hokoj9Uke"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
